### ISSUE TITLE
BGA support

### ISSUE THREAD

**Issue by dtinth** [bemusic/bemuse#295]
Scratchpad

```scss
  &--video-bg {
    width: 100%;
    height: 100%;
    position: absolute;
    top: -48px;
    left: 0;
    z-index: 11;
    opacity: 0;
    transition: 0.5s opacity;
    will-change: opacity;
    &.is-playing {
      opacity: 1;
    }
  }
```
